buildcss:
	@echo "  [BUILDCSS] root/css                                       > root/css/lizztcms.css"
	@cat yui/sam-skin.css yui/table-editor.css dragdrop/context-menu.css dragdrop/drag-drop-folder-tree.css widgets/jscalendar.css global.css theme1.css tipsy.css jqueryui/jquery-ui.css chosen.css > lizztcms.css
